### ISSUE TITLE
Image broken

### ISSUE THREAD

**Issue by umanusorn** [pattomotto/EZKeychain#2]
![image](https://user-images.githubusercontent.com/1754362/43066545-26c0cb40-8e8f-11e8-9f6f-f7c2bd6e80c8.png)

**Comment by PattoMotto** [comment]
It's beyond my control :)

[AlamoFire](https://github.com/alamofire/alamofire) also have this problem.

![image](https://user-images.githubusercontent.com/1745000/43068069-8a466bd0-8e93-11e8-88a6-19dd90a78a7f.png)
